on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Reproduce the analysis
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['v1.5.4']
        os: [macOS-latest, windows-latest, ubuntu-latest]
      max-parallel: 1

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Install matplotlib"
        run: pip3 install matplotlib
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Install packages"
        run: julia -p 1 src/install_packages.jl
        shell: bash
      # - name: "Run a script"
      #   run: julia -p 1 src/script1.jl
      #   shell: bash
  