on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Reproduce the analysis
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['v1.6.0']
        os: [macOS-latest, windows-latest, ubuntu-latest]
      max-parallel: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: "Install matplotlib"
        run: pip3 install matplotlib
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Install packages"
        run: julia -p 1 src/install_packages.jl
        shell: bash
      # - name: "Press analysis"
      #   run: julia -p 1 src/pipeline.jl
      #   shell: bash
      # - name: "Press analysis"
      #   run: julia -p 1 julia src/fig_press.jl
      # - name: "Pulse analysis"
      #   run: julia -p 1 julia src/fig_pulse.jl
  